spring:
  data:
    mongodb:
      port: 27017
      host: localhost
      username: root
      password: root
      database: conversion_dev
      authentication-database: admin
  webflux:
    problemdetails:
      enabled: true